"""add_billing_tables

Revision ID: 02409bad14b0
Revises: 043584e51dc0
Create Date: 2026-03-21 08:36:07.419735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa: F401
import sqlmodel # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02409bad14b0'
down_revision: Union[str, None] = '043584e51dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_customers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('update_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_customers_stripe_customer_id'), 'stripe_customers', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('ix_stripe_customers_user_id'), 'stripe_customers', ['user_id'], unique=True)
    op.create_table('stripe_payments',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_payment_intent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('update_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_payments_stripe_payment_intent_id'), 'stripe_payments', ['stripe_payment_intent_id'], unique=True)
    op.create_index(op.f('ix_stripe_payments_user_id'), 'stripe_payments', ['user_id'], unique=False)
    op.create_table('stripe_subscriptions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('stripe_subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('billing_period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_period_start', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_period_end', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('update_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['tier_id'], ['membership_tiers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_subscriptions_stripe_subscription_id'), 'stripe_subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_stripe_subscriptions_user_id'), 'stripe_subscriptions', ['user_id'], unique=False)
    op.add_column('membership_tiers', sa.Column('stripe_product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('membership_tiers', sa.Column('stripe_price_monthly_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('membership_tiers', sa.Column('stripe_price_yearly_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('membership_tiers', sa.Column('price_monthly_display', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('membership_tiers', sa.Column('price_yearly_display', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # Remove Stripe columns from membership_tiers
    op.drop_column('membership_tiers', 'price_yearly_display')
    op.drop_column('membership_tiers', 'price_monthly_display')
    op.drop_column('membership_tiers', 'stripe_price_yearly_id')
    op.drop_column('membership_tiers', 'stripe_price_monthly_id')
    op.drop_column('membership_tiers', 'stripe_product_id')

    # Drop billing tables
    op.drop_index(op.f('ix_stripe_subscriptions_user_id'), table_name='stripe_subscriptions')
    op.drop_index(op.f('ix_stripe_subscriptions_stripe_subscription_id'), table_name='stripe_subscriptions')
    op.drop_table('stripe_subscriptions')
    op.drop_index(op.f('ix_stripe_payments_user_id'), table_name='stripe_payments')
    op.drop_index(op.f('ix_stripe_payments_stripe_payment_intent_id'), table_name='stripe_payments')
    op.drop_table('stripe_payments')
    op.drop_index(op.f('ix_stripe_customers_user_id'), table_name='stripe_customers')
    op.drop_index(op.f('ix_stripe_customers_stripe_customer_id'), table_name='stripe_customers')
    op.drop_table('stripe_customers')

    # EE tables (auditlog, scorm*, payments*, ssoconnection) are NOT recreated
    # in downgrade — they live outside this migration's scope.
